name: My First automated deployment Pipeline 


on:
  push:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform                                                                      
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: ECS-project-end2end/terraform/modules/clusters
      run: terraform init

    - name: Terraform Format
      working-directory: ECS-project-end2end/terraform/modules/clusters
      run: terraform fmt -check

    - name: Terraform Plan
      working-directory: ECS-project-end2end/terraform/modules/clusters
      run: terraform plan -input=false
      continue-on-error: false

    - name: Terraform Apply
      if: github.event_name == 'push'
      working-directory: ECS-project-end2end/terraform/modules/clusters
      run: terraform apply -auto-approve -input=false