name: Build and push docker image to ECR

on:
  push:
    branches:
    - main

jobs:
   build:
      runs-on: ubuntu-latest
     
      steps: 
      - name: checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        run: ${{ steps.aws-access.outputs.Configure-AWS-credentials }}


      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ID }}
        continue-on-error: false

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AWS_ID }}/yderder_latest:latest .

      - name: Tag Docker image
        run: |
          docker tag yderder_latest:latest ${{ secrets.AWS_ID }}/yderder_latest:latest

      - name: Push Docker image to AWS ECR
        run: |
          docker push ${{ secrets.AWS_ID }}/yderder_latest:latest




