name: My First automated deployment Pipeline 


on:
    workflow_run:
      workflows: ["Build and push docker image to ECR"]  
      types:
        - completed

jobs:
  build:

    runs-on: ubuntu-latest
        

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure-AWS-credentials
      id: aws-access
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform                                                                      
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd terraform 
        terraform init

    - name: Terraform Format
      run: |
        cd terraform 
        terraform fmt --recursive -check

    - name: Terraform Plan
      run: |
        cd terraform 
        terraform plan -refresh=true -input=false
      continue-on-error: false

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: |
        cd terraform 
        terraform apply -auto-approve -input=false